// <auto-generated />
namespace StorageBox.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ModifiedSBTaskCreatedIsValidfieldImplementedvalidationofitemget : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifiedSBTaskCreatedIsValidfieldImplementedvalidationofitemget));
        
        string IMigrationMetadata.Id
        {
            get { return "201610051808463_Modified SBTask. Created IsValid field. Implemented validation of item get."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
