// <auto-generated />
namespace StorageBox.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Somethingchangedinsbtaskmodel3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Somethingchangedinsbtaskmodel3));
        
        string IMigrationMetadata.Id
        {
            get { return "201610011730292_Something changed in sbtask model 3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
